services:
  last-AWS-db:
    image: postgres:15-alpine
    container_name: last-AWS-db
    restart: always
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_aws:/var/lib/postgresql/data

  aws-web:
    build: .
    container_name: last-AWS-web
    restart: always
    env_file:
      - ./env/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/last-AWS
    environment:
      POSTGRES_INITDB_ARGS: "-U admin -c CREATE DATABASE last_aws;"
      DJANGO_SETTINGS_MODULE: settings.base

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  postgres_data_aws:
