version: '3.9'

services:
  last-AWS-db:
    image: postgres:15-alpine
    container_name: last-AWS-db
    restart: always
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_aws:/var/lib/postgresql/data

  aws-web:
    build: .
    container_name: last-AWS-web
    restart: always
    env_file:
      - ./env/.env
    ports:
      - "8000:8000"
    depends_on:
      - last-AWS-db
      - redis
    volumes:
      - .:/last-AWS
    command: gunicorn settings.wsgi:application --bind 0.0.0.0:8000

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  postgres_data_aws:
