name: Django Deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: POSTGRES_HOST,POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,DJANGO_SECRET_KEY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_STORAGE_BUCKET_NAME,AWS_S3_REGION_NAME
          script: |
            cd ~/Team4-Last-Backend
            git pull origin main
            export DJANGO_SETTINGS_MODULE=settings.production
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            export AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}
            pkill -f gunicorn || true
            source ~/.pyenv/versions/aws/bin/activate
            python manage.py migrate
            gunicorn settings.wsgi:application --bind 0.0.0.0:8000 --workers 3 --daemon
            echo "âœ… Deployment completed!"